### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by ipa-vsp** [ipa-vsp/any_robot_worker#1]
- [x] #2
- [ ] Cartesian motion via yaml
- [ ] Switching planners
- [ ] Integrating with camera.
- [ ] Collision checking and add or remove objects.
- [ ] Hand to eye calibration [doc](https://ros-planning.github.io/moveit_tutorials/doc/hand_eye_calibration/hand_eye_calibration_tutorial.html) and [repo](https://github.com/ros-planning/moveit_calibration)
- [ ] Robot Description
- [ ] Behaviour tree
